# Site Settings
name: Libro de Motes
title: Libro de Motes de Damas y Caballeros
description: Edición digital del Libro de motes de damas y cavalleros. Intitulado El juego de mandar. Compuesto por don Luis Milán
tags:
show_hero: true
menu:
  - title: A
    url: /A1
  - title: B
    url: /B1
  - title: C
    url: /C1
  - title: D
    url: /D1
  - title: E
    url: /E1
  - title: F
    url: /F1
  - title: G
    url: /G1
  - title: H
    url: /H1
  - title: J
    url: /J1
  - title: K
    url: /K1
  - title: L
    url: /L1
  - title: M
    url: /M1
  - title: N
    url: /N1
email: julieta.gold@gmail.com

# Social Media Settings
# Remove the item if you don't need it
github_username: jgoldsmidt
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/LM-Libro-de-Motes" 
url: "http://jgoldsmidt.github.io"
google_analytics: "UA-XXXXXXXX-X"
language: "sp"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2
